ExMod-Team/EXILED

EXILED/Exiled.API/Features/Player.cs

Currently there is a bug where Clearing a Player's inventory drops some amount of ammunition. 
This is due to `BodyArmorUtils.RemoveEverythingExceedingLimits` getting called in `OnRemoved` in `InventorySystem.Items.Armor.BodyArmor`
Meaning that when the items are cleared, and armor gets removed, any additional ammo that cannot be carried will be dropped first, so when `ClearAmmo` is called it doesn't remove the dropped ammo

Clear Ammo before Clearing Items

---

EXILED/Exiled.API/Extensions/MirrorExtensions.cs
EXILED/Exiled.API/Features/Server.cs

Added to Server.cs the WhitelistedPlayers
Added to MirrorExtensions.cs SetIntercomDisplayTextForTargetOnly and ResetIntercomDisplayText
WhitelistedPlayers allows to add and modify current player whitelisted
SetIntercomDisplayTextForTargetOnly is a FakeSyncVar that allows to modify for specific target
ResetIntercomDisplayText just Resync the FakeSyncVar

`[Exiled::API]` Added WhitelistedPlayers, SetIntercomDisplayTextForTargetOnly and ResetIntercomDisplayText

---

EXILED/Exiled.API/Features/Items/Jailbird.cs
EXILED/Exiled.Events/EventArgs/Item/ChargingJailbirdEventArgs.cs
EXILED/Exiled.Events/EventArgs/Item/SwingingEventArgs.cs
EXILED/Exiled.Events/Patches/Fixes/Jailbird914CoarseFix.cs

Also Add Jailbird Propperty inside SwingingEvent

Fix `Jailbird::WearState`

---

.github/workflows/pull_request_opened.yml
EXILED/Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs

Same behavior, less bloat, except for the primary check:
// Remove original "No scp can touch" logic.
newInstructions.RemoveRange(0, 3);
if (!ply.IsHuman() || ply.HasBlock(BlockedInteraction.GrabItems))
{
return;
}
That has been returned, presuming the client won't even send the request if it's not a human. If this behavior should be re-introduced, just add the RemoveRange back.
Works fine, redundant code - SCP changed since original design. 
In theory same behavior. 
No
<br />
<br />
- 
If there is a desire to …

InteractingScp330.cs: Reduction of bloat code from original design.

---

EXILED/Exiled.Events/EventArgs/Player/ChangingItemEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/Healing.cs

(initial PR) https://github.com/Exiled-Official/EXILED/pull/128
- Fixed `Healed` event when `player is null`, example error:
```
NullReferenceException: Object reference not set to an instance of an object
Exiled.Events.EventArgs.Player.HealedEventArgs..ctor (Exiled.API.Features.Player player, System.Single lastAmount) (at <f4c00fd0d7e8475ab3c3400f59529cfe>:0)
(wrapper dynamic-method) PlayerStatsSystem.HealthStat.PlayerStatsSystem.HealthStat.ServerHeal_Patch0(PlayerStatsSystem.HealthStat,single)
(wrapper dynamic-method) InventorySystem.Items.Usables.Medkit.InventorySystem.Items.Usables.Medkit.OnEffectsActivated_Patch1(InventorySystem.Items.Usables.Medkit)
InventorySystem.Items.Usables.Consumable.ActivateEffects () (at <e1b23ebe5ae54d29b01902bb36299308>:0) …
```

[Events] Fix null reference

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

Fix Custom Role Classes giving custom ammo when they are not suppose to. Moved giving custom ammo to the addrole method instead of changing role event.
Custom ammo is given when the custom role class changes to a new role without losing their role in the changing role event. This causes players to re get their custom ammo if they 914 swap classes (with plugins) or escape. Using the changing role event was a fix that joker made for dropping excess ammo awhile back ago but x3rt pr'd a change already that fixed the underlying issue of that. 
Custom ammo is only given when they first become the role. 
**Does this PR introduce a …

Fix custom role classes giving custom ammo when they are not suppose to

---

EXILED/Exiled.API/Features/Npc.cs
EXILED/Exiled.API/Features/Player.cs

Fix NpcNoclip that can't be moved
<br />
<br />

FixNpcNoclip

---

EXILED/Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs

Skill issue (Or rather my scp server does not compile with error, for whatever reason).
Compile bug
Interact event compiles correctly (I am going to assume Yamato double checked but someone else should too).
No
Yamato and I went back and forth on why my scp instance did not throw a compile error for this, but did for his pr that resolves a bug, no idea why. The only difference is windows versions, and system's themselves. Even built on his branch + changes I did not get a compile error …

Interacting scp330 compile fix

---

EXILED/Exiled.Events/EventArgs/Scp330/InteractingScp330EventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs

I barely understand what exactly second part of 330interaction transpiler does, but still rewrote it as I found it simpler
Surely sever logic is fine, but affects the sound rpc
Make ev.Sever work without breaking rpc
no
@louis1706 @Undid-Iridium im not sure i did that correctly, thats what my patch do:
<br />
<br />

`Scp330` sound fix

---

EXILED/Exiled.API/Features/Player.cs

- little sendstaffmessage fix
broke
repair
<br />
<br />

Little StaffMessageFix

---

EXILED/Exiled.Events/EventArgs/Item/KeycardInteractingEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Item/KeycardInteracting.cs

Implements `KeycardPickup.Permissions` to working with throwing/dropping keycard pickup
Ew😭
Ee😎
Nope
I cant do that easier, bcs base game `CheckPermissions` method, checks `ItemBase`, not permissions itself🥲
<br />
<br />

`KeycardPickup.Permissions` now is not joke

---

EXILED/Exiled.Events/EventArgs/Server/UnbannedEventArgs.cs
EXILED/Exiled.Events/EventArgs/Server/UnbanningEventArgs.cs
EXILED/Exiled.Events/Handlers/Server.cs
EXILED/Exiled.Events/Patches/Events/Server/Unban.cs

Adding some new events
<br />
<br />

`[Exiled::Events]` `Unbanning` and `Unbanned` events

---

EXILED/Exiled.API/Features/Items/Armor.cs
EXILED/Exiled.API/Features/Pickups/BodyArmorPickup.cs
EXILED/Exiled.Events/Patches/Generic/StaminaRegen.cs
EXILED/Exiled.Events/Patches/Generic/StaminaRegenArmor.cs

Adds the possibility to change the StaminaRegen, found the method by
https://discord.com/channels/656673194693885975/663978314683252777/1274815767342223431
It cannot be set but only get that default is 1f
The Armor can regen faster the Stamina
Nope
<br />
<br />

`[EXILED::API]` Adding StaminaRegenMultiplier (BodyArmor)

---

EXILED/Exiled.Events/Patches/Fixes/NWFixDetonationTimer.cs

Fixes https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/396
Games just takes the first Scenario, 120 seconds and just uses that if the value is not the same as one of the scenarios
Takes the nearest number from the Scene loaded from the game
Just as it showing i replicated the issue from the report but fixing it and showing the default game behavior
Shouldn't
(I've checked if in the config or in some way is changed but doesn't seem)
The code is big and a mess because …

`[EXILED::EVENTS]` Fixing bug report n.396

---

EXILED/Exiled.API/Features/Map.cs

- Added `IsDecontaminationEnabled` property at Exiled.API.Features.Map
Redacted comment at `Exiled.API.Features.Map.StartDecontamination` to clarify the connection between the command in the RA console and the method (from `Starts the light containment zone decontamination process` to `Forces the light containment zone decontamination process`)
- Exiled only allows Force the Decontamination process
- Exiled allows Enable, Disable and Force Decontamination process
- No
<br />
<br />

Added IsDecontaminationEnabled property

---

EXILED/Exiled.CustomItems/Commands/List/List.cs
EXILED/Exiled.CustomRoles/Commands/List/List.cs

Using the Custom Item and Custom Roles list commands will execute the registered list if there is no argument.
Needless to write registered for a list command and Custom Roles does not say that the ``customrole list abilities`` command exists.
Typing the command without arguments will execute the registered command of the list command.
Testing result:
<br />
<br />

``[Exiled::CustomRoles]`` ``[Exiled::CustomItems]`` QoL in List commands.

---

EXILED/Exiled.Events/Patches/Events/Scp330/DroppingCandy.cs

Candy is removed before event could be cancelled. Remove code is now called after. 
Candy is removed before event could be cancelled. 
N/A
N/A
<br />
<br />
- [?] I have tested my changes and it worked as expected

DroppingScp330 Event Fix.

---

EXILED/Exiled.API/Features/Plugin.cs
EXILED/Exiled.Events/Commands/Config/EConfig.cs
EXILED/Exiled.Events/Commands/Config/Merge.cs
EXILED/Exiled.Events/Commands/Config/Split.cs
EXILED/Exiled.Events/Commands/PluginManager/Disable.cs
EXILED/Exiled.Events/Commands/PluginManager/Enable.cs
EXILED/Exiled.Events/Commands/PluginManager/Patches.cs
EXILED/Exiled.Events/Commands/PluginManager/PluginManager.cs
EXILED/Exiled.Events/Commands/PluginManager/Show.cs
EXILED/Exiled.Events/Commands/Reload/All.cs
EXILED/Exiled.Events/Commands/Reload/Configs.cs
EXILED/Exiled.Events/Commands/Reload/GamePlay.cs
EXILED/Exiled.Events/Commands/Reload/Permissions.cs
EXILED/Exiled.Events/Commands/Reload/Plugins.cs
EXILED/Exiled.Events/Commands/Reload/Reload.cs
EXILED/Exiled.Events/Commands/Reload/RemoteAdmin.cs
EXILED/Exiled.Events/Commands/Reload/Translations.cs

Adding a new way to register commands for parent commands. Iirc this is system which is similar to nw
No breaking changes cuz both systems are supported (new and current)
~(but for me this is better)~
<br />
<br />

`[Exiled::API]` New way to register parent commands

---

.github/labeler.yml
EXILED/Exiled.API/Features/Npc.cs

Use `ID_Dedicated` or `null` to ensure an NPC is VSR Compliant (Uses Unverified/DedicatedHost instances, which will not take up slots or show on the Player List)
None
None
No
Original PR Done in the previous repo and imported inside apis-rework as asked by the suggestion i added it back and made it available for the next versions of Exiled
https://github.com/Exiled-Team/EXILED/pull/2297
I stripped the other functionality
<br />
<br />

Allow `ID_Dedicated`/`null` for `Npc.UserId` Parameter

---

EXILED/Exiled.Events/EventArgs/Player/InteractingLockerEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/InteractingLocker.cs

**Fixes SrLitch crash** 
I'm not writing all this, it has been tested and works.

SrLitch crash fix

---

EXILED/Exiled.Events/Patches/Events/Item/KeycardInteracting.cs

Fix
bad
good
✖️
**Other information**: 😭😭😭
<br />
<br />

Fix keycard throw interaction

---

EXILED/Exiled.Events/Commands/Hub/Install.cs

This PR fixes the NWAPI plugin installation with the `hub install` command.
`hub install` fetches every single asset in the plugin release and downloads it.
`hub install` will now filter assets with the `-NWAPI` postfix in the name.
No.
-
<br />
<br />

`[EXILED::Events]` Fix downloading NWAPI plugins with `hub install`

---

EXILED/Exiled.API/Features/Items/Scp330.cs
EXILED/Exiled.Events/EventArgs/Scp330/InteractingScp330EventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs

Fixing `InteractingScp330EventArgs::Candy`
Candy is incorrect
#118
Candy is correct
<br />
<br />

Fix `InteractingScp330EventArgs::Candy`

---

EXILED/Exiled.Events/Patches/Events/Server/Reporting.cs
EXILED/Exiled.Loader/Loader.cs

Fix: ReportingCheater event is now called before NW event (#99)
Feat: Specifying which component is outdated (#53)
<br />
<br />

Bug fix + request

---

EXILED/Exiled.Events/Patches/Fixes/VoiceChatTpsFix.cs

Added TpsFix

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

```cs
protected virtual void UnsubscribeEvents()
{
...
Exiled.Events.Handlers.Player.Destroying += new CustomEventHandler<DestroyingEventArgs>(OnDestroying);
}
```
I don't think it's correct
<br />
<br />

Strange CustomRole:UnsubscribeEvents()

---

EXILED/Exiled.API/Features/Spawn/RoomSpawnPoint.cs
EXILED/Exiled.CustomItems/CustomItems.cs
EXILED/Exiled.CustomItems/Events/MapHandler.cs

Fixes RoomSpawnPoint when used in Surface and also changing the spawn eventarg to WaitingForPlayers.
Proof what the change is working and dont brake the position
PillsSpawnPoints its a List of RoomSpawnPoints where some are in Surface
<br />
<br />

Fix RoomSpawnpoint

---

EXILED/EXILED.props
EXILED/Exiled.API/Extensions/RoleExtensions.cs
EXILED/Exiled.API/Features/Player.cs

Add IsScp to Role Extensions to easily check if the Role is an SCP role, I noticed there was .IsHuman and .IsAlive, but no .IsScp which could be useful to some people
You either have to do !RoleTypeId.IsHuman && RoleTypeId.IsAlive or RoleTypeId.Team == Team.SCPs to check if the team is SCPs
You can now check with RoleTypeId.IsScp to see if the team is an SCP team or not.
No, nobody will need to change anything if they don't want to.
<br />
<br />

Add role checks (like IsScp) to Role Extensions / RoleTypeId

---

EXILED/Exiled.API/Extensions/RoleExtensions.cs

`RoleExtensions.IsMilitary()` returns true for guards, this is because the official wiki classifies them as militant classes 
https://en.scpslgame.com/index.php?title=Humans
https://en.scpslgame.com/index.php?title=Facility_Guard
`RoleExtensions.IsMilitary()` returns false for guards
`RoleExtensions.IsMilitary()` returns true for guards as well
<br />
<br />

Update RoleExtensions.IsMilitary to reflect how the wiki categorizes guards

---

EXILED/Exiled.Events/Handlers/Player.cs

@Mikihero and I were discussing what all 3 of the item events do (Using, Used and UsingComplete) and it was confusing what did what, so Miki did some testing and this PR is to include all items that trigger what event and clearer documentation of what each event does exactly, as it currently looks like Used and UsingComplete are the same thing.
<br />
<br />

docs: clearer documentation on item events

---

EXILED/Exiled.API/Features/Items/Scp330.cs
EXILED/Exiled.Events/EventArgs/Scp330/InteractingScp330EventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs

Fixing InteractingScp330EventArgs::Candy
Candy is incorrect
Candy is correct
No.
<br />
<br />

Scp330 interacting fix

---

EXILED/EXILED.props
EXILED/Exiled.CustomItems/Commands/Give.cs
EXILED/Exiled.CustomRoles/Commands/Give.cs

Commands currently evaluate only `*`, `all`, or `Player.Id`
Commands now evaluate players based on `RAUtils.ProcessPlayerIdOrNamesList` (eg `@player.17.15`) as well as `*`, `all`, or `Player.Id`.
No breaking changes
<br />
<br />

Updated CustomItems & CustomRoles give commands to use default RAUtils.ProcessPlayerIdOrNamesList

---

EXILED/Exiled.API/Features/Player.cs
EXILED/Exiled.API/Features/Roles/DestroyedRole.cs
EXILED/Exiled.API/Features/Roles/Role.cs

Add a new "destroyed" role and fix #202 #203
<br />
<br />

14.0 role fixes

---

EXILED/Exiled.API/Enums/DoorType.cs
EXILED/Exiled.API/Features/Doors/Door.cs

https://github.com/orgs/ExMod-Team/projects/1/views/1?pane=issue&itemId=88769592&issue=ExMod-Team%7CEXILED%7C198
Breaking change, probably
<br />
<br />
-

Hcz bulk door fix

---

EXILED/Exiled.Events/Patches/Events/Scp330/InteractingScp330.cs

Scp330Interact was failing due to local variable shifts
<br />
<br />

Scp330 interobject fix

---

EXILED/Exiled.Events/EventArgs/Player/SpawningEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/Spawning.cs

Due to logic changes OldRole was removed, ev.Player.Role can be used instead and NewRole was added. 
* Fix #215 
<br />
<br />

Fixing SpawningEventArg

---

EXILED/Exiled.Events/Patches/Events/Server/RestartingRound.cs

Per title. Will change back to transpiler once NW fixed their skill issue.
<br />
<br />

Temp fix for RestartingRound

---

EXILED/Exiled.API/Features/Lift.cs
EXILED/Exiled.Events/EventArgs/Scp079/ElevatorTeleportingEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp079/ElevatorTeleporting.cs
EXILED/Exiled.Events/Patches/Generic/LiftList.cs

Rework the patch of ElevatorTeleporting event.
Rework the patch that handles Lift.List.
Activating an elevator as SCP-079 make the player crash.
<br />
<br />

Fix `Exiled.Events.EventArgs.Scp079.ElevatorTeleportingEventArgs` & Lift.List empty

---

EXILED/Exiled.API/Extensions/RoleExtensions.cs
EXILED/Exiled.API/Features/Roles/Role.cs
EXILED/Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs
EXILED/Exiled.Events/Patches/Generic/IndividualFriendlyFire.cs

Fix Flashbang & HE

---

EXILED/Exiled.API/Features/Doors/BreakableDoor.cs
EXILED/Exiled.API/Features/Doors/CheckpointDoor.cs
EXILED/Exiled.API/Features/Doors/Door.cs
EXILED/Exiled.API/Interfaces/IDamageableDoor.cs

**What is the current behavior?** None
**What is the new behavior?**
Add Door.Repair :trollface: 
<br />
<br />

Add Door.Repair

---

EXILED/Exiled.Events/Patches/Generic/IndividualFriendlyFire.cs

Moved the patch (from red to green) for custom FF to make it not trigger for certain damage handlers. Those damage handlers shouldn't cause self-damage.
Jailbird can damage the owner cuz we skip NW check.
Jailbird will not damage the owner
<br />
<br />

Individual ff

---

EXILED/Exiled.API/Features/PrefabHelper.cs
EXILED/Exiled.Events/Events.cs
EXILED/Exiled.Events/Handlers/Internal/ClientStarted.cs
EXILED/Exiled.Events/Handlers/Internal/MapGenerated.cs

Handles StartedClient event to register prefabs and change methods.
<br />
<br />

Rework PrefabHelper

---

EXILED/Exiled.API/Features/Player.cs

Overload two operators `==` & `!=` to `Player` class and add `Equals` and `GetHashCode`.
Fix comparison between two player instances.
<br />
<br />

Fix Player comparison

---

EXILED/Exiled.API/Features/Items/Item.cs
EXILED/Exiled.API/Features/Items/Scp1344.cs
EXILED/Exiled.Events/EventArgs/Interfaces/IScp1344Event.cs
EXILED/Exiled.Events/EventArgs/Scp1344/ChangedStatusEventArgs.cs
EXILED/Exiled.Events/EventArgs/Scp1344/ChangingStatusEventArgs.cs
EXILED/Exiled.Events/EventArgs/Scp1344/DeactivatedEventArgs.cs
EXILED/Exiled.Events/EventArgs/Scp1344/DeactivatingEventArgs.cs
EXILED/Exiled.Events/EventArgs/Scp1344/TryingDeactivatingEventArgs.cs
EXILED/Exiled.Events/Handlers/Scp1344.cs
EXILED/Exiled.Events/Patches/Events/Scp1344/Deactivating.cs
EXILED/Exiled.Events/Patches/Events/Scp1344/Status.cs

**What is the current behavior?** None
**What is the new behavior?*
Adds the ChangingStatus, ChangedStatus, TryingDeactivating, Deactivating, Deactivated events.
Adds Scp1344 Item
<br />
<br />

Add Scp1344 Events and Scp1344 Item

---

EXILED/Exiled.Events/Patches/Events/Player/ChangingRoleAndSpawned.cs

The eventargs for ChangingRole could be null sometimes (if player not verified), which breaks ChangeInventory method.
<br />
<br />

Fix ChangingRoleAndSpawned

---

EXILED/Exiled.Loader/Loader.cs
EXILED/Exiled.Loader/Updater.cs

Per title. The updater should work properly now.
<br />
<br />

Exiled loader fix and version number display style change

---

EXILED/Exiled.CustomItems/API/Features/CustomItem.cs

Removing typeLookupTable in Customitems
When attempting to create multiple `CustomItem` instances of the same type, an exception was thrown. The type is not a unique property for creating a dictionary.
typeLookupTable is exists
no more typeLookupTable 😈
no
<br />
<br />

Removing typeLookupTable

---

EXILED/Exiled.Events/EventArgs/Player/ShotEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/Shot.cs

Added new Shot patch
Current Shot patch is using Physics.Raycast in its constructor and is missing crucial CanHurt field that is widely used in plugins
Mentioned issues are fixed
Yes, it removes MaxDistance field from ShotEventArgs. This field is just as relevant as including raycast mask in the event (not at all)
<br />
<br />

New Shot patch

---

EXILED/Exiled.Events/EventArgs/Scp330/DroppingScp330EventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp330/DroppingCandy.cs

Remove Scp330Bag setter and fix ev.Candy always None.
<br />
<br />

Fix DroppingCandy event

---

EXILED/Exiled.Events/EventArgs/Server/EndingRoundEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Server/RoundEnd.cs

- Replace base game logic with `LeadingTeam leadingTeam = ev.LeadingTeam`
- This fix getter & setter of ev.LeadingTeam
- Remove IsRoundEnded (IsAllowed do the same)
- ev.LeadingTeam always return FacilityForces (represents 0)
- ev.LeadingTeam setter doesn't work
- unneeded property in the event
- ev.LeadingTeam return the correct LeadingTeam
- set ev.LeadingTeam change the team that win the round
- IsRoundEnded is now IsAllowed
<br />
<br />

Fix EndingRound event

---

EXILED/Exiled.API/Extensions/RoleExtensions.cs
EXILED/Exiled.API/Features/Player.cs
EXILED/Exiled.API/Features/Respawn.cs
EXILED/Exiled.API/Features/Roles/HumanRole.cs
EXILED/Exiled.API/Features/Waves/TimedWave.cs
EXILED/Exiled.API/Features/Waves/WaveTimer.cs
EXILED/Exiled.Events/EventArgs/Map/AnnouncingChaosEntranceEventArgs.cs
EXILED/Exiled.Events/EventArgs/Map/AnnouncingNtfEntranceEventArgs.cs
EXILED/Exiled.Events/EventArgs/Server/RespawningTeamEventArgs.cs
EXILED/Exiled.Events/EventArgs/Server/SelectingRespawnTeamEventArgs.cs
EXILED/Exiled.Events/Events.cs
EXILED/Exiled.Events/Handlers/Map.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingChaosEntrance.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingNtfEntrance.cs
EXILED/Exiled.Events/Patches/Events/Server/AddingUnitName.cs
EXILED/Exiled.Events/Patches/Events/Server/SelectingRespawnTeam.cs

Updated EXILED to new game update
NW have removed SpawnableTeamType so yeah, we are breaking everything!
NW are trying to not break game every major beta update (impossible).
I'll finish this PR tomorrow or if someone else wants to fix `AnnouncingNtfEntrance` I can assist
<br />
<br />

New game update

---

EXILED/Exiled.API/Features/Waves/TimedWave.cs
EXILED/Exiled.API/Features/Waves/WaveTimer.cs
EXILED/Exiled.Events/EventArgs/Server/SelectingRespawnTeamEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Server/RespawningTeam.cs
EXILED/Exiled.Events/Patches/Events/Server/SelectingRespawnTeam.cs

* Add `Base` property to `TimedWave` & `WaveTimer`
* Change default property of `IsAllowed` of selecting team event to `true`
* Call `Base` property in each transpiler of the respecting fixed event
When you don't change anything, players aren't able to respawn. If you set IsAllowed to true of selecting, the server crashes.
Fixed all of these problems.
<br />
<br />

fix: fix respawning and selecting team events that make server crash

---

EXILED/Exiled.Events/EventArgs/Map/AnnouncingChaosEntranceEventArgs.cs
EXILED/Exiled.Events/EventArgs/Map/AnnouncingNtfEntranceEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingChaosEntrance.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingNtfEntrance.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingTeamEntrance.cs

- Add `TargetMethods` to each transpiler of these events since we can't use multiple harmonypatch attribute at the same place.
- Fix `ev.IsAllowed` for the both events.
- Add a new transpiler to prevent cassie from playing if the string builder is empty.
- Other changes.
- Announcing events aren't called for mini waves.
- ev.IsAllowed doesn't work.
- Some properties setter make the server crashes.
- ..
- Fix all above.
<br />
<br />

fix: fix announcing ntf/chaos entrance events

---

EXILED/Exiled.API/Features/DamageHandlers/GenericDamageHandler.cs
EXILED/Exiled.API/Features/Items/Jailbird.cs
EXILED/Exiled.API/Features/Items/MicroHid.cs
EXILED/Exiled.API/Features/Pickups/MicroHIDPickup.cs
EXILED/Exiled.CustomItems/API/Features/CustomGrenade.cs
EXILED/Exiled.Events/EventArgs/Player/ChangingMicroHIDStateEventArgs.cs
EXILED/Exiled.Events/EventArgs/Player/UsingMicroHIDEnergyEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Map/FillingLocker.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangingMicroHIDState.cs
EXILED/Exiled.Events/Patches/Events/Player/InteractingLocker.cs
EXILED/Exiled.Events/Patches/Events/Player/UsingMicroHIDEnergy.cs
EXILED/Exiled.Events/Patches/Events/Scp3114/Slapped.cs
EXILED/Exiled.Events/Patches/Events/Scp939/PlayingFootstep.cs
EXILED/Exiled.Events/Patches/Events/Server/RoundEnd.cs
EXILED/Exiled.Events/Patches/Fixes/LockerFixes.cs

No Christmas changes here. They'll be on other branch
<br />
<br />

feat!: Update for new release

---

EXILED/Exiled.API/Features/Player.cs
EXILED/Exiled.Events/EventArgs/Player/SpawningEventArgs.cs

Fixes all problems for comparing destroyed player [related bug](https://discord.com/channels/656673194693885975/1320839832628494388)
broke💔
fix👍
no🥹
<br />
<br />

fix: Player comparing (`GetHashCode`)

---

EXILED/Exiled.API/Features/Toys/Speaker.cs

Adds some import methods and properties to the Speaker toy
<br />
<br />

feat: Speaker update

---

EXILED/Exiled.Events/EventArgs/Item/ChangingMicroHIDPickupStateEventArgs.cs
EXILED/Exiled.Events/EventArgs/Player/ChangingMicroHIDStateEventArgs.cs
EXILED/Exiled.Events/Handlers/Item.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangingMicroHIDState.cs

It turns out that microhid state changes can now happen independent from player, like when microhid is pickup
So:
- Optimized `ChangingMicroHIDStateEventArgs` to not get item by serial(and iterating all items😅).
- Added `ChangingMicroHIDPickupStateEventArgs` (in `Item` namespace)
Above
Above
No💔
<br />
<br />

fix: microhid events

---

EXILED/Exiled.API/Features/Player.cs
EXILED/Exiled.API/Features/TeslaGate.cs

*Player.IsSpeaking:* `IsSpeaking` is client-side lol. Use `ServerIsSending` instead
*TeslaGate.IsPlayerInHurtRange:* `sizeOfKiller` is size for killer `Bounds` (not a range between player and tesla gate)
[VoiceChatting event results](https://cdn.discordapp.com/attachments/957552253768708096/1321508534520905811/image.png?ex=676d7e3b&is=676c2cbb&hm=727afe5881b7435a0d9926fd00a541815f46c24d209dcbfc7a2ec234e107dc2c&)
Above
No
<br />
<br />

fix: Player.IsSpeaking and TeslaGate.IsPlayerInHurtRange

---

EXILED/Exiled.Events/Patches/Fixes/FixNWDisarmCommand.cs

fix: FixNWDisarmCommand

---

EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs

Fixed SS nre
Play stupid games win stupid prizes
It just works
It does not
<br />
<br />

fix: SS NullReferenceException

---

EXILED/Exiled.API/Features/Player.cs

https://discord.com/channels/656673194693885975/1002713309876854924/1317978520701501482
The Player.SetFakeScale method now no longer checks if the proposed fakeScale is the current real scale of the player.
The current behaviour does not allow for the fakeScale to be reset e.g.
The current behaviour does allow for the fakeScale to be reset
<br />
- [ x] Bug fix (non-breaking change which fixes an issue)
<br />

fix: SetFakeScale doesnt execute with currentScale

---

EXILED/Exiled.API/Features/Lockers/Locker.cs
EXILED/Exiled.CustomItems/API/Features/CustomItem.cs

Fixing the brain-washing of 𝗩𝗔𝗟𝗘𝗥𝗔𝟳𝟳𝟭 in customitem
Closes #356
the pickup its locked when spawning in a locker
work
no
I am sleepy
Code test is in the discord bug-report.
<br />
<br />

fix: LockerSpawnpoint in CustomItem

---

EXILED/Exiled.API/Features/Scp914.cs
EXILED/Exiled.Events/Handlers/Internal/Round.cs

Fixes Exiled.API.Features.Scp914.Scp914InputObject return nothing
Important: Rn function returns LightRooms (UnityEngine.GameObject) inside HashSet<GameObject> inside914. idk if it should. but list of players and pickups is correct, there is just 1 addtional gameobject in array function is returning. Like this:
[tst] 4 2 1
[tst] LightRooms (UnityEngine.GameObject)
[tst] Player(Clone) (UnityEngine.GameObject)
[tst] Player(Clone) (UnityEngine.GameObject)
[tst] FirearmPickup(Clone) (UnityEngine.GameObject)
first number - total array size, second number - players array size, third - pickups array size. logged total array
Fixes Exception in OnWaitingForPlayers
returns nothing,
gives exception …

fix: Exiled.API.Features.Scp914.Scp914InputObject return nothing & Exception in OnWaitingForPlayers

---

EXILED/Exiled.Events/Patches/Events/Player/DroppingAmmo.cs

Updated the invoke method from `OnDroppedItem` to `OnDroppedAmmo`in the DroppingAmmo patch.
invoke `OnDroppedItem`
invoke `OnDroppedAmmo`.
`DropAmmo `will no longer invoke `DroppedItem`
<br />
- [may] Breaking change (fix or feature that would cause existing functionality to change)
<br />

fix: "OnDroppedAmmo" event does not trigger

---

EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs

Stops settingbase from deleting all other settings on register
Deletes all settings except the last one registered
Keeps all settings
No
<br />

fix: setting base deleting all other settings

---

EXILED/Exiled.Events/Patches/Events/Map/PlacingBulletHole.cs

fixed some transpiler errors
returns raycast origin position instead of hit position because of transpiler error
returns raycast hit position
No
<br />
<br />
- [?] Still requires more testing

fix: PlacingBulletHoleEventArgs::Position

---

EXILED/Exiled.API/Features/Items/Item.cs
EXILED/Exiled.API/Features/Items/Usable.cs
EXILED/Exiled.API/Features/Pickups/Pickup.cs
EXILED/Exiled.API/Features/Pickups/Projectiles/Projectile.cs
EXILED/Exiled.API/Features/Player.cs

feat: Pr133 Usable change

---

EXILED/Exiled.API/Features/Room.cs
EXILED/Exiled.Events/Patches/Generic/DoorList.cs

fix: `Room::NearestRooms` fix

---

EXILED/Exiled.CustomItems/API/Features/CustomWeapon.cs

- Added a check to try get value from the dictionary instead of accessing it for how much ammo is in player inventory.
- Accesses the dictionary directly which could cause an error since this event runs after the ammo is loaded into the gun.
- Uses a try get value to get the ammo if it cant find it defaults to 0.
No
N/A
<br />
<br />

fix: Potential Error Fix With Custom Weapon Reloading

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

Fixed custom roles lagging back by using spawned event.
People spawning custom roles through custom role api spawn system will lag back because of using spawning event.
Fixes issue by using spawned event.
No
N/A
<br />
<br />

fix: Fix Custom Roles Lagging Back When Spawning

---

EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs

Adds a function to send specific settings to a specific player. This could be useful when you want to send settings depending on an event that gets triggered. I.e. supporter only benefits that you check via group, which isn't set during the OnVerified event.
Can't send specific settings to specific players, have to use SendToAll and that could break in very specific cases.
<br />
<br />

feat: send to player specific settings

---

EXILED/Exiled.Events/Patches/Events/Map/ExplodingFlashGrenade.cs

fix: Npc cant get flashed

---

EXILED/Exiled.CustomItems/API/Features/CustomWeapon.cs

- Fixed players being able to exploit custom items to not get the intended clipsize amount by switching off the weapon quickly after reloading. 
- Player can exploit by switching off weapon quickly after reloading. 
- Player can't exploit. 
No
N/A
<br />
<br />

fix: Player Custom Firearm Reloading Exploit

---

EXILED/Exiled.API/Extensions/EffectTypeExtension.cs

- Added SCP-1344 to IsPositive Extension for effects.
- SCP-1344 isn't part of IsPositive even though its a positive effect. 
- SCP-1344 effect is now part of IsPositive. 
No
N/A
<br />
<br />

fix: Add SCP-1344 Effect to IsPositive Extension

---

EXILED/Exiled.API/Features/Toys/AdminToy.cs
EXILED/Exiled.API/Features/Toys/ShootingTargetToy.cs

**Describe the changes**
Added GameObject and Transform properties to AdminToy for convinience
Transform and GameObject have to be accesses through .Base (e.g. primitive.Base.transform)
Transform and GameObject can be accessed directly through Exiled AdminToys
<br />
<br />

feat: added GameObject and Transform properties to AdminToy

---

EXILED/Exiled.Events/EventArgs/Player/BanningEventArgs.cs
EXILED/Exiled.Events/EventArgs/Player/KickingEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/Banning.cs
EXILED/Exiled.Events/Patches/Events/Player/Kicking.cs

**Describe the changes**
This pull request adds ICommandSender to Kicking and Banning EventArgs. This might be useful when devs make a custom CommandSender class that contains extra data (e.g. DiscordCommandSender), but currently it just gets turned into Server.Host in the events.
😭
😊
It does not
<br />
<br />

feat: Added ICommandSender to Kicking/Banning EventArgs

---

EXILED/Exiled.Events/Handlers/Internal/Round.cs

Fixing a NW Bug https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/947

fix: Fix NW Hypothermia bug

---

EXILED/Exiled.Events/Patches/Events/Player/SendingValidGameConsoleCommand.cs
EXILED/Exiled.Events/Patches/Events/Player/SendingValidRACommand.cs

Fix for SendingValidCommand events for DotCommand and RACommand
<br />
<br />

fix: Command events fix

---

EXILED/Exiled.Events/Patches/Fixes/RemoteAdminNpcCommandAddToDictionaryFix.cs

Added a transpiler for `SpawnDummyCommand.Execute` that adds a created NPC to the `Npc.List` (`Player.Dictionary`).
Spawning an NPC via RA does not add it to the `Npc.List` (`Player.Dictionary`).
Spawning an NPC via RA adds it to the `Npc.List` (`Player.Dictionary`).
No.
-
<br />
<br />

feat: Spawning NPCs via RA adds them to the `Npc.List`

---

EXILED/Exiled.Events/Patches/Events/Player/IntercomSpeaking.cs

When IsAllowed = false, a start sound was produced, which should not be there.
I changed the event call location from IntercomState.Starting to IntercomState.Ready after receiving the ReferenceHub 
Highly unlikely.
<br />
<br />

fix: IntercomSpeaking event

---

EXILED/Exiled.API/Features/Roles/Scp939Role.cs
EXILED/Exiled.Events/Config.cs
EXILED/Exiled.Events/Handlers/Internal/Round.cs
EXILED/Exiled.Events/Patches/Generic/StayAtAmnesticCloud.cs

…cCloud
Added a property `TurnedPlayers` to `Scp939Role`.
adding a `Player` to it will make the `Player` **immune** to the `AmnesticCloud`.
No
I basically copied `Exiled.Events.Patches.Generic.ParseVisionInformation`, thanks!
<br />
<br />

feat: Added a list of players who are turned away from SCP-939 AmnesticCloud

---

EXILED/Exiled.API/Features/Player.cs

Added a method to remove candy from a `Player` instance.
There is a method `Player::TryAddCandy(CandyKindID)`, but no method to remove candy.
Added a method to remove candy from a `Player` instance.
No.
<br />
<br />

feat: `Player::TryRemoveCandy(CandyKindID)` method

---

EXILED/Exiled.API/Features/Map.cs
EXILED/Exiled.Events/Patches/Fixes/RemoteAdminNpcCommandAddToDictionaryFix.cs

Added overload for Map.Broadcast(ushort, Func<Player, string>) to shorthand map-wide broadcasting.
Map-wide broadcast with Player::DisplayNickname
Map-wide broadcast with Player::DisplayNickname
No.
<br />
<br />

feat: Map.Broadcast(ushort, Func<Player, string>) overload.

---

EXILED/Exiled.API/Enums/MessageType.cs
EXILED/Exiled.API/Features/Message.cs
EXILED/Exiled.API/Features/Player.cs

A useful API for server owners and developers. Now there will be no need to limit user's choice between Hint and Broadcast when developing a plugin

feat: Add Message API

---

EXILED/Exiled.API/Features/Player.cs

**Describe the changes**
Changes "return if the effect has been Enable." to "A bool indicating whether the effect was valid and successfully enabled." as the former made no grammatical sense.
**What is the current behavior? (You can also link to an open issue here)**
It makes no grammatical sense
https://discord.com/channels/656673194693885975/1350404844292411405/1350404844292411405
**What is the new behavior? (if this is a feature change)**
It makes grammatical sense, using the same return as the other EnableEffects returns.
*Made it target the correct branch by the request from Yamato* …

docs: Grammatical Corrections for a EnableEffect (but it targets the right branch)

---

EXILED/Exiled.API/Enums/EffectType.cs

Updated the descriptions for AmnesiaItems and AmnesiaVision to reflect their current functionality.
AmnesiaItems: Did not clearly state that it prevents using medical items.
AmnesiaVision: Lacked a clear explanation of SCP-939's invisibility.
AmnesiaItems: Prevents players from using medical items.
AmnesiaVision: Makes SCP-939 invisible to affected players, with visibility briefly restored when damaged or attacking.
<br />
<br />

docs: Update Descriptions for AmnesiaItems and AmnesiaVision

---

EXILED/Exiled.Events/EventArgs/Player/MicroHIDOpeningDoorEventArgs.cs
EXILED/Exiled.Events/Handlers/Player.cs
EXILED/Exiled.Events/Patches/Events/Player/MicroHIDOpeningDoor.cs

feat: Add new event MicroHIDOpeningDoorEventArgs

---

EXILED/Exiled.API/Extensions/MirrorExtensions.cs
EXILED/Exiled.API/Features/Items/Item.cs
EXILED/Exiled.API/Features/Player.cs

Brings back PlayGunSound extension
Currently volume of sound is very low. Seems like it depends on gun position but idk how to move gun closer to player so it will work (creating instance in Server.Host inv and move it to player doesn't work). I hope that someone has an idea how to do this
<br />
<br />
- [+-] I have tested my changes and it worked as expected

fix: PlayGunSound Extensions fix

---

EXILED/Exiled.API/Features/Player.cs

Added a method to apply health regeneration to players via `RegenerationProcess`, allowing for customizable delay, rate, duration, speed multiplier, and HP multiplier.
No built-in or easily accessible method to apply custom regeneration effects to players through EXILED.
Players can now receive configurable health regeneration via `AddRegeneration()` extension method.
No breaking changes. New functionality added in a backward-compatible way.
Designed as an extension for easier …

feat: New Player::AddRegeneration method

---

EXILED/Exiled.CustomItems/API/Features/CustomItem.cs

**Describe the changes**  
Fixed `UnregisterItems` to avoid modifying `Registered` during iteration by using a copy.
**What is the current behavior?**  
`UnregisterItems` logs an `InvalidOperationException` when `TryUnregister` modifies `Registered`.
**What is the new behavior?**  
Iterates over a copy of `Registered`, preventing the error.
**Does this PR introduce a breaking change?**  
No, no changes needed for users.
**Other information**:  
Fixes a collection iteration error.
<br />
<br />

fix: InvalidOperationException in UnregisterItems

---

EXILED/Exiled.Events/EventArgs/Map/SpawningRoomConnectorEventArgs.cs
EXILED/Exiled.Events/Handlers/Map.cs
EXILED/Exiled.Events/Patches/Events/Map/SpawningRoomConnector.cs

new event for changing the door connector type
none
new event
the elevators break when changing connectortype
<br />
<br />

feat: changing connectors

---

EXILED/Exiled.CustomItems/API/Features/CustomArmor.cs
EXILED/Exiled.CustomItems/API/Features/CustomWeapon.cs

Adding AmmoLimits, CategoryLimits to CustomArmor
Damage in CustomWeapon not neccessary now, defualt NaN to not override (can be 0 dmg)
-
Can change the ammo and category limit in Armor
Can do 0 damage in custom weapon
None
<br />
<br />

feat: Custom limits for armor & virtual dmg for customweapon

---

EXILED/Exiled.Events/EventArgs/Scp173/UsingBreakneckSpeedsEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp173/UsingBreakneckSpeeds.cs

Adds a new argument to the usingbreakneckspeed event so that we can determine whether the capability is opening or closing
Adding IsActivationRequested args to UsingBreakneckSpeeds event
Nope
<br />
<br />

feat: New argument specifying whether breakneckspeed is turned on or off

---

EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs

> A method to register SSSS to specified player
> Currently we need to use predicate and loop
> A new overloads to `Register` and `Unregister` methods with `player` argument
> No
<br />
<br />

feat: add methods to register and unregister SSSS to specified players

---

EXILED/Exiled.Events/EventArgs/Scp1344/ChangedStatusEventArgs.cs
EXILED/Exiled.Events/EventArgs/Scp1344/ChangingStatusEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Scp1344/Status.cs

Removed the incorrect and unused IsAllowed argument from the Scp1344.ChangedStatus event.
Refactored the ChangingStatus (prefix) and ChangedStatus (postfix) patches into a unified transpiler implementation.
The ChangedStatus event incorrectly includes an IsAllowed argument, which is not used and may cause confusion.
Event hooks are separated and not streamlined within a single transpiler.
Events are now handled within a single, unified transpiler for better clarity and control.
The ChangedStatus event has been cleaned up to include only relevant data.
**Does this PR introduce a breaking change?** (What changes might users need to …

feat: Fix wrong arg & Scp1344 Status change Prefix/Postfix to Transpiler

---

EXILED/Exiled.API/Features/Toys/Speaker.cs

Adds a new Speaker instantiate method that allows you to bind with a transform
Right now, you can only spawn based on a position, not a transform, so you can't stick it to the transform.
Allows you to create a Speaker based on a transform
<br />
<br />

feat(Speaker): add transform create

---

EXILED/Exiled.Events/Patches/Events/Scp079/ChangingCamera.cs

fix: ChangingCamera event

---

EXILED/Exiled.CustomItems/API/Features/CustomWeapon.cs

Fixed custom weapons insta killing players if their damage was set below 0.
Players get insta killed by custom weapons that are set to below 0 damage.
If a custom weapon damage is set to below 0 it will use the weapons default damage.
No
N/A
<br />
<br />

fix: custom weapons not doing default damage when set to below 0

---

EXILED/Exiled.Events/Patches/Events/Scp173/BeingObserved.cs

fix: fix being observed calling in reverse

---

EXILED/Exiled.Events/Patches/Events/Player/DroppingItem.cs

- Due to LabAPI adding PlayerDroppingItemEventArgs the index of the ItemPickupBase local has been shifted up one.
Incorrect local is used (LabAPI's PlayerDroppingItemEventArgs is passed to the DroppedItemEventArgs ctor)
Correct local is used (ItemPickupBase is passed to the  DroppedItemEventArgs ctor)
No
<br />
<br />

Fix DroppedItem Event

---

EXILED/Exiled.Installer/Program.cs

fix: Update RepoID to reflect new repository identifier

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs
EXILED/Exiled.Events/Events.cs
EXILED/Exiled.Events/Handlers/Internal/Round.cs

Fix critical error
When die as a custom role which is like role = none it kicks the player out of the server without giving any error, even when player log back in, get a black screen and nothing loads. Causes client error!
Fixed
No
https://discord.com/channels/656673194693885975/1375431933844262952/1375431933844262952
<br />
<br />

fix: Critical CustomRole api Error & Invalid ragdoll error

---

EXILED/Exiled.API/Features/Map.cs

This PR fixes a bug in RemainingDecontaminationTime calculation. It incorrectly used Mathf.Min instead of Mathf.Max, causing the property to always return 0.
RemainingDecontaminationTime consistently returns 0 due to Mathf.Min(0, ...) being used.
RemainingDecontaminationTime now correctly returns the positive remaining time by using Mathf.Max(0, ...) to ensure accurate duration display.
None. This is a bug fix correcting existing behavior.
<br />
<br />

fix: RemainingDecontaminationTime is wrong

---

EXILED/Exiled.Events/EventArgs/Scp914/UpgradedInventoryItemEventArgs.cs
EXILED/Exiled.Events/EventArgs/Scp914/UpgradedPickupEventArgs.cs
EXILED/Exiled.Events/Handlers/Scp914.cs
EXILED/Exiled.Events/Patches/Events/Scp914/UpgradedItem.cs
EXILED/Exiled.Events/Patches/Events/Scp914/UpgradedPickup.cs
EXILED/Exiled.Events/Patches/Events/Scp914/UpgradedPlayer.cs
EXILED/Exiled.Events/Patches/Events/Scp914/UpgradingPickup.cs
EXILED/Exiled.Events/Patches/Events/Scp914/UpgradingPlayer.cs

To use result(items), I add **UpgradedPickup** and **UpgradedInventoryItem** EventArgs
good
very good (I add new parameter "result")
no
please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass this pr i need it. please pass …

feat: Add UpgradedInventoryItem and UpgradedPickup on Scp914

---

EXILED/Exiled.API/Enums/AspectRatioType.cs
EXILED/Exiled.API/Extensions/FloatExtensions.cs
EXILED/Exiled.API/Features/Player.cs
EXILED/Exiled.Events/EventArgs/Player/ChangedRatioEventArgs.cs
EXILED/Exiled.Events/Handlers/Player.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangedAspectRatio.cs

Added ChangedRatio event to detect when a player's aspect ratio changes.
Currently, Exiled has no way to detect or handle player aspect ratio changed.
New event triggers when player's aspect ratio changes, provides both old and new ratio values.
❌ No , This is purely additive functionality
<br />
<br />

feat: New Changed Aspect Ratio Event & Player::AspectRatio Property

---

EXILED/Exiled.API/Extensions/DamageTypeExtensions.cs
EXILED/Exiled.API/Extensions/ItemExtensions.cs
EXILED/Exiled.CustomItems/API/Features/CustomWeapon.cs

Modify code to unify with **IsWeapon**
<br />
<br />

fix: Fix IsWeapon() did not check for jailbird

---

EXILED/Exiled.API/Features/Workstation.cs
EXILED/Exiled.Events/Patches/Generic/WorkstationListAdd.cs

Add new class on Exiled.API.Features
There is no Workstation class
**Workstation**
nope
<br />
<br />

feat: Add Exiled.API.Features.Workstation

---

EXILED/Exiled.CustomRoles/API/Extensions.cs
EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs
EXILED/Exiled.CustomRoles/CustomRoles.cs
EXILED/Exiled.CustomRoles/Events/PlayerHandlers.cs

I changed the system custom roles spawn. The old way was causing many problems like server crashes, unfair selection, broken features and the random chance was not really random. So I moved all the logic to a central place in PlayerHandlers. The new logic uses a proper weighted system to choose roles based on their SpawnChance and it also handles the no role chance correctly. Additionally, the logic for selecting a custom spawn position has been refactored to ensure it is statistically fair.
Currently the server can crash if you have two roles with 100 chance for the same class because they race each other. Also when it works, the selection is not fair, it just picks the first role that …

feat: Rework and Fix Custom Role Spawn Logic & Limits

---

EXILED/Exiled.API/Features/Ragdoll.cs

Added features to Exiled.API.Features.Ragdoll class and optimized the code.
Created a Ragdoll within the server network and it worked fine.
Destroy(), Spawn() Add function overloading (allowing more interaction within a function)
❌ (still not)
<br />
<br />

feat: Add Ragdoll features & readability

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

Fixes bug with custom roles spawn system
ignores limit for spawn
do not give custom role if limit was reached
no
<br />
<br />

fix: bug with not tracking limit of spawned players in custom roles

---

EXILED/Exiled.Events/EventArgs/Scp049/FinishingSenseEventArgs.cs
EXILED/Exiled.Events/Handlers/Scp049.cs
EXILED/Exiled.Events/Patches/Events/Scp049/FinishingSense.cs

Adding Sense Finishing event for Scp049
No
If the sense ability ends with the target dying, the cooldown is not applied properly. (I don't know if is still the same.)
<br />
<br />

feat: New Scp049 Finishing Sense Event

---

EXILED/Exiled.Events/EventArgs/Player/EscapingEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/EscapingAndEscaped.cs

Exiled Broken Labapi event fix different way
Because the previous fix broke the custom item escape handler or other conditions that check isallowed. Instead, I brought isallowed to normally return false and not break labapi. Now it comes after exiled labapi, and if isallowed is not true, it can return without breaking labapi.
No
<br />
<br />

fix: Escaping Exiled and LabAPI bug different way

---

EXILED/Exiled.API/Enums/DamageType.cs
EXILED/Exiled.API/Features/DamageHandlers/GenericDamageHandler.cs
EXILED/Exiled.API/Features/Player.cs

Removes an unnecessary Hurt method overload and introduces a new configurable behavior for Cassie announcements triggered by player deaths.
Cassie announcements are triggered on any player death . Additionally, the Hurt method had two overloads, which was unnecessary and potentially confusing. Also, there was no way to override Cassie behavior per Hurt call.
Developers can now choose to annoucment Cassie messages for non SCPs by setting overrideCassieForAllRole to true. Only one clean, flexible overload of Hurt remains, simplifying the API surface and supporting all use cases via optional parameters.
**Does this PR introduce a …

feat: Generic damage handler add new value

---

EXILED/Exiled.API/Features/Respawn.cs

Wave related functions have been added to the Respawn class.
PauseWaves(), RestartWaves() worked fine, but We couldn't configure the detailed Wave.
PauseWave(), RestartWave() functions have been added, and one more PauseWaves(), RestartWaves() function has been added to make it easier to set Wave details.
x
<br />
<br />

feat: Add Wave related functions to Respawn

---

EXILED/Exiled.Events/Events.cs
EXILED/Exiled.Events/Handlers/Server.cs

feat: All players spawned2

---

EXILED/Exiled.CustomItems/API/Features/CustomWeapon.cs

I fixed a small nullability issue then changed the methods directly using base game SetAmmo methods to use Exileds methods (which check the AmmoType to be valid)
Scp 127's AmmoType is 255 for exiled cuz NW never added an official ammo for 127. Because of this, when a Custom Weapon 127 reloads and calls OnInternalReloaded, it would do ev.Player.Inventory.ServerSetAmmo(args); and cause the client to desync because the use AmmoType was None
Why didn't Ttrouble just use ev.Player.SetAmmo 😭 …

fix: Custom Scp127 clipsizes causing desyncs

---

EXILED/Exiled.API/Features/Pickups/FirearmPickup.cs

Fixes a bug where firearm pickups spawned in had no ammo
When spawning most firearms, they don't have any ammo inside of them
Appears to work with revolvers and shotguns too
<br />
<br />

fix: Firearm pickups spawning without ammo

---

EXILED/Exiled.API/Features/Core/UserSettings/ButtonSetting.cs
EXILED/Exiled.API/Features/Core/UserSettings/DropdownSetting.cs
EXILED/Exiled.API/Features/Core/UserSettings/HeaderSetting.cs
EXILED/Exiled.API/Features/Core/UserSettings/KeybindSetting.cs
EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs
EXILED/Exiled.API/Features/Core/UserSettings/SliderSetting.cs
EXILED/Exiled.API/Features/Core/UserSettings/TwoButtonsSetting.cs
EXILED/Exiled.API/Features/Core/UserSettings/UserTextInputSetting.cs

Adds the new features from the new update to Exiled setting classes (and obsolete old ctors)
Cant test functionality cuz no client build
Can you guys take a look at the Update methods? Those were the best ideas I had to implement the new stuff, if you find anything confusing lmk, I'd like to get the docs to be descriptive
<br />
<br />

feat: more SSS for 14.1.3

---

EXILED/Exiled.Events/EventArgs/Player/JumpingEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Item/ReceivingPreference.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingScpTermination.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangedRoom.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangingRadioPreset.cs
EXILED/Exiled.Events/Patches/Events/Player/Jumping.cs

I fix
Big error
No error
Still cant test the functionality of patches cuz client version isn't out
<br />
<br />

fix: ReceivingPreference, AnnouncingScpTermination, ChangedRoom, and Jumping transpilers and patches

---

EXILED/Exiled.Events/Patches/Fixes/CheaterReportFix.cs

Made a transpiler to fix a broken method cuz of NW
method doesnt work. https://git.scpslgame.com/northwood-qa/scpsl-bug-reporting/-/issues/1814
method works
If NW fixes this, my transpiler should print an error indicating that the transpiler needs to be fixed or is obsolete
<br />
<br />

fix: CheaterReport.SubmitReport not working

---

EXILED/Exiled.Events/Patches/Events/Player/Jumping.cs

Just trust me 😭 
<br />
<br />

fix: Fall damage not working

---

EXILED/Exiled.API/Features/DamageHandlers/DamageHandlerBase.cs
EXILED/Exiled.API/Features/DamageHandlers/GenericDamageHandler.cs
EXILED/Exiled.Events/Patches/Events/Map/AnnouncingTeamEntrance.cs

Fixed AnnouncingNtfEntrance and AnnouncingChaosEntrance showing subtitles when event was denied, as well as GenericDamageHandler throwing NRE in LabAPI ServerEvents.OnCassieQueuingScpTermination from CassieAnnouncement when no subtitles were provided to the ctor
A few issues
Less issues
no
Overriding CassieDeathAnnouncement might break stuff, but I can't figure out any cases where that'd happen (nor have I seen Cassie behaving weird)
<br />
<br />

fix: Cassie fixes

---

EXILED/Exiled.API/Features/Intercom.cs

Verify grammar and if we use this Method name or we improve them ?

feat: Add Intercom TrySetOverride(Player, bool) and HasOverride(Player)
