ExMod-Team/EXILED

.github/README.md

replace all `Exiled-Official` with `ExMod-Team`

Update README.md to match with new repo

---

EXILED/Exiled.API/Features/Player.cs

Removed breaking changes from player
~~Removing it~~
<br />
<br />

`[Exiled::API]` Removing breaking changes

---

EXILED/Exiled.API/Features/Npc.cs

Fix Player.Position -> FpcRole.Relative Position -> Repeat
``Player.Position`` will call ``FpcRole.RelativePosition`` which will repeat back to ``Player::Position``
Use the correct variable
<br />
<br />

Fix repeated calls

---

EXILED/Exiled.API/Features/Player.cs

Fix a breaking change in #9 
Plugin throwing exception
Plugin will no longer throw exception
Nope
<br />
<br />

Fix breaking change

---

EXILED/Exiled.API/Features/Pickups/Pickup.cs
EXILED/Exiled.API/Features/Pickups/Projectiles/Scp018Projectile.cs

Optimize scp018 properties setters, obsolete setting pickup PhysicsModule, bacause thats not normal thing and we should not allow this in public api in my opinion
-
-
-
<br />
<br />

`Scp018projectile` chages

---

EXILED/Exiled.Events/Patches/Events/Scp079/Recontaining.cs

Title bruh
Not working
Working
<br />
<br />

Fixing `Recontaining` event patch

---

EXILED/Exiled.API/Features/Lockers/Chamber.cs
EXILED/Exiled.Events/EventArgs/Map/FillingLockerEventArgs.cs
EXILED/Exiled.Events/EventArgs/Player/InteractingLockerEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/InteractingLocker.cs

Editing other classes so they use Exiled locker
Obsoleted all properties that need to be removed in exiled 9
I'm waiting for suggestions for other names in InteractingLockerEventArgs
<br />
<br />

Using lockers everywhere

---

.github/workflows/push_nuget.yml

Pushing Nuget package to GitHub registry
<br />
<br />

Github Packages

---

EXILED/Exiled.Events/Patches/Events/Scp079/Recontaining.cs
EXILED/Exiled.Events/Patches/Generic/DoorList.cs

fix things that crash server
crash 
not crash 
<br />
<br />

[Events] Fix crash

---

EXILED/Exiled.API/Features/Items/Firearm.cs
EXILED/Exiled.API/Features/Items/Usable.cs
EXILED/Exiled.API/Features/Player.cs
EXILED/Exiled.Events/EventArgs/Server/UnbannedEventArgs.cs
EXILED/Exiled.Events/EventArgs/Server/UnbanningEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Server/Unban.cs

- Optimized `Firearm::ChangeOwner` method
- Fixed `Usable::CreatePickup` for creating pickup form usable that owns `Server::Host
- Fixed items removing from `Item.List`, for `player::RemoveItem(..., false)`
- Fixed general `Unbanning(ed)` events logic (id is userId, not an BanDetails stings representation)
<br />
<br />

Random fixes

---

EXILED/Exiled.Events/Commands/Hub/Hub.cs
EXILED/Exiled.Events/Commands/Hub/HubApi/ApiProvider.cs
EXILED/Exiled.Events/Commands/Hub/HubApi/Models/HubPlugin.cs
EXILED/Exiled.Events/Commands/Hub/Install.cs
EXILED/Exiled.Events/Exiled.Events.csproj
EXILED/Exiled.Loader/LinuxPermission.cs

This PR introduces new `hub install` command to download plugins from the EXILED Hub.
This is a new feature.
<br />
<br />

`[EXILED::Events]` Introduce `hub install` command

---

.github/workflows/dev.yml
.github/workflows/main.yml
.github/workflows/push_nuget.yml
.github/workflows/release.yml
EXILED/Exiled/Exiled.nuspec

nuget rename

---

EXILED/Exiled.Loader/AutoUpdateFiles.cs

Recompile exiled with latest build deps.
<br />
<br />

Halloween Update

---

EXILED/Exiled.Events/Patches/Events/Player/ChangingRoleAndSpawned.cs

Fixing Spawned event
Spawned event calls on LocalHub
Spawned event doesn't call on LocalHub
<br />
<br />

`[Exiled::Events]` Spawned event fix

---

EXILED/Exiled.API/Enums/EffectType.cs
EXILED/Exiled.API/Extensions/EffectTypeExtension.cs

wtf is `OrangeWitness`💀

---

EXILED/Exiled.API/Features/Lockers/Chamber.cs
EXILED/Exiled.API/Features/Lockers/Locker.cs

add gameobject and trasform to lockers
no😥😫😫😫❎❌❌❌❗❗
yes✅✅✅✅✅
no
<br />
<br />

[Exiled.API] add gameobject and trasform to lockers

---

EXILED/Exiled.Events/Patches/Events/Player/ChangingRoleAndSpawned.cs

Fixing spawned event
NRE
No nRE
<br />
<br />

Fixing `Spawned` event on dev

---

EXILED/Exiled.Events/Patches/Events/Map/PlacingBulletHole.cs
EXILED/Exiled.Events/Patches/Events/Player/EnteringKillerCollision.cs

Fix PlacingBulletHole

---

EXILED/Exiled.API/Features/Room.cs

Room toString fix
<br />
<br />

Room toString fix

---

EXILED/Exiled.CustomItems/API/Features/CustomItem.cs
EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

Fix CustomItems / CustomRoles errors
Those 2 methods will create erros when player is destroyed
No
<br />
<br />

CustomItems and CustomRoles fix

---

EXILED/Exiled.Events/EventArgs/Scp330/InteractingScp330EventArgs.cs
EXILED/Exiled.Events/Patches/Events/Server/RestartingRound.cs

Fix InteractingScp330

---

EXILED/Exiled.Events/Patches/Events/Player/Shot.cs
EXILED/Exiled.Events/Patches/Events/Server/RestartingRound.cs

Fix Shot event

---

EXILED/Exiled.Events/Patches/Events/Player/ChangingItem.cs
EXILED/Exiled.Events/Patches/Events/Server/RestartingRound.cs

Corrected the index
<br />
<br />

Fix ChangingItem patch

---

EXILED/Exiled.Events/EventArgs/Player/ShotEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/Shot.cs

Change the method patched to handle all possibilites.
The OnShot event is only called when a IDestructible is hit.
The OnShot event is called every time a player shot with a firearm.
Yes
<br />
<br />

Fix OnShotEvent

---

EXILED/Exiled.Events/Patches/Events/Player/VoiceChatting.cs

Fix the voicechatting event patch
<br />
<br />

Fix VoiceChatting event (VoiceMessage setter)

---

EXILED/Exiled.API/Enums/DisruptorMode.cs
EXILED/Exiled.Events/EventArgs/Player/ChangingDisruptorModeEventArgs.cs
EXILED/Exiled.Events/Handlers/Player.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangingDisruptorMode.cs

New event
I've tried to implement IsAllowed but seems that new value is not synced with client (system seems a bit strange for me but ok)
<br />
<br />

feat: ChangingDisruptorMode event

---

EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs

fix: Possible fix of NRE in SSSS

---

EXILED/Exiled.API/Features/Core/UserSettings/SettingBase.cs

Changed a letter 🤓. 
Nothing.
No.
<br />
<br />

docs: fixed a letter in the summary of ``bool TryGetSetting<T>(Player, int, out T)``

---

EXILED/Exiled.Events/EventArgs/Player/ReloadingWeaponEventArgs.cs
EXILED/Exiled.Events/EventArgs/Player/UnloadingWeaponEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/ReloadingWeapon.cs
EXILED/Exiled.Events/Patches/Events/Player/UnloadingWeapon.cs
EXILED/Exiled.Example/Events/PlayerHandler.cs

fix: Reloading/Unloading weapon events

---

.github/README.md

Localized German in readme.
Still the same.
German -> Deutsch
No.
<br />
<br />

docs: Localized German

---

EXILED/Exiled.API/Features/Toys/Light.cs

Changed the descriptions of the LightShape and LightType properties in Exiled.API.Features.Toys.Light to better represent what they actually do (rather than copy pasted code that wasn't updated when 14.0 came out)
The current descriptions are misleading
No, just changes the descriptions of the properties to help dev's who don't know how to mess with Light's
<br />
<br />

docs: Update Light Toy property descriptions

---

EXILED/Exiled.Events/Patches/Events/Player/DryFire.cs

fixed transpiler hook and commented unused one, corrected docs
fires constantly
fires when it needs to fire
No
<br />
<br />
- [?] Still requires more testing

fix: DryFiring fired constantly

---

EXILED/Exiled.API/Features/Npc.cs

feat: Fix NPC Spawn

---

EXILED/Exiled.API/Features/Toys/Light.cs

Adds the property ShadowType to Exiled.API.Features.Toys.Light to let developers interact with the shadows of a light without directly using Light::Base
❌❌❌❌❌
✅✅✅✅✅📈📈📈📈📈
❌
nameless said if my addition built for the xmas-2024 branch and worked there I could create a PR to dev with the same change so technically I haven't tested this on its intended version of SL, but it works for xmas-2024
<br />
<br />

feat: ShadowType

---

EXILED/Exiled.API/Features/Player.cs

Has NPCs in Player.List like the poll wanted.
NPCs arent in Player.List which makes them unusable for testing.
NPCs are now in Player.List
No
<br />
<br />

feat: Have NPC In Player List

---

EXILED/Exiled.API/Enums/DoorLockType.cs

Fixed Typo: Isloation to Isolation
<br />

docs: Typo in DoorLockType.cs

---

EXILED/Exiled.API/Features/Player.cs

fix: CurrentItem for MicroHID

---

EXILED/Exiled.API/Enums/DoorType.cs

fix: NeverExistDoor

---

EXILED/Exiled.API/Features/Map.cs

Add Map.StaffMessage(string, Player)
<br />
<br />

feat: StaffMessage(string, Player)

---

EXILED/Exiled.Events/Patches/Events/Player/InteractingDoor.cs

fix: InteractingDoorEvent::CanInteract

---

EXILED/Exiled.API/Features/Server.cs

- changed RefreshServerName() to RefreshServerNameSafe() for better error handling and efficiency yk
💔💔💔💔💔💔💔 
https://discord.com/channels/656673194693885975/1362031043867312301
🤑🤑🤑🤑🤑🤑🤑
❌❌❌❌❌
<br />
<br />

fix: Server.Name refresh method

---

EXILED/Exiled.Events/Patches/Events/Player/ActivatingWarheadPanel.cs

fix: activating warhead panel event fix

---

EXILED/Exiled.CustomItems/API/Features/CustomKeycard.cs
EXILED/Exiled.Events/Patches/Events/Scp914/UpgradingPlayer.cs

fix: CustomKeycard being blank and particle disruptor crashing

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

fix: Custom role ragdoll validate correction

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

added a check if GotRoleHint is actually enabled
hint shows regardless of whether it is enabled/disabled
hint shows only when its enabled in config
no
<br />
<br />

fix: CustomRoles GotRoleHint.Show config

---

EXILED/Exiled.Events/EventArgs/Player/DiedEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/DyingAndDied.cs

**Describe the changes**
Add ragdoll to died event
😥😥😥😥😥😥😥😥😥😥
😍😍😍😍😍😍😍😍😍😍
<br />
<br />

feat: Add ragdoll to died event

---

EXILED/Exiled.Events/EventArgs/Player/ChangingDisruptorModeEventArgs.cs
EXILED/Exiled.Events/Patches/Events/Player/ChangingDisruptorMode.cs

fix for ChangingDisruptorMode transpiler location
Not right there/ Broken not firing event
X
<br />
<br />

fix: ChangingDisruptorMode transpiler location

---

EXILED/Exiled.CustomRoles/API/Features/CustomRole.cs

Fix
No fix
Yes fix
No Fix
Yes Fix
<br />
<br />

fix: CustomRole keep position on spawn

---

EXILED/Exiled.Example/Events/PlayerHandler.cs

fix: Quick Fix
